# Gauss Elmination

In [112]:
import numpy as np

def gaussElimin(a,b):
    n = len(b)
  # Elimination Phase
    for k in range(0,n-1): #iterate on rows
        for i in range(k+1,n): 
           if a[i,k] != 0.0:
               lam = a [i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               b[i] = b[i] - lam*b[k]
                
  # Back substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [113]:
A = np.array([[1,1,-2],[0,1,-1],[3,-1,1]])
display(A)

b = np.array([-3,-1,4])
display(b)

gaussElimin(A,b)

array([[ 1,  1, -2],
       [ 0,  1, -1],
       [ 3, -1,  1]])

array([-3, -1,  4])

array([1, 2, 3])

# Doolitle Decomposition

In [114]:
def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
           if a[i,k] != 0.0:
               lam = a [i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               a[i,k] = lam
    return a #Return the combined matrix LU

def LUsolve(a,b):
    #a contains the matrix LU
    n = len(a)
    #LY=B forward substitution (b is replaced with the solution of Y)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
    #UX=Y backward substitution (b=Y is replaced with the solution of X)
    b[n-1] = b[n-1]/a[n-1,n-1]    
    for k in range(n-2,-1,-1):
       b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b


A = np.array([[1,1,-2],[0,1,-1],[3,-1,1]])
display(A)

b = np.array([-3,-1,4])
display(b)

LU=LUdecomp(A)
display(LU)

display(LUsolve(LU,b))

array([[ 1,  1, -2],
       [ 0,  1, -1],
       [ 3, -1,  1]])

array([-3, -1,  4])

array([[ 1,  1, -2],
       [ 0,  1, -1],
       [ 3, -4,  3]])

array([1, 2, 3])

# choleski descomposition

In [115]:
import numpy as np
import math

def choleski(a):
    n = len(a)
    for k in range(n):
        try:
            a[k,k] = math.sqrt(a[k,k] - np.dot(a[k,0:k],a[k,0:k]))
        except ValueError:
            raise Exception('Matrix is not positive definite')
        for i in range(k+1,n):
            a[i,k] = (a[i,k] - np.dot(a[i,0:k],a[k,0:k]))/a[k,k]
    for k in range(1,n): a[0:k,k] = 0.0 #erase upper triangle
    return a

def choleskiSol(L,b):
    n = len(b)
  # Solution of [L]{y} = {b}  
    for k in range(n):
        b[k] = (b[k] - np.dot(L[k,0:k],b[0:k]))/L[k,k]
  # Solution of [L_transpose]{x} = {y}      
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(L[k+1:n,k],b[k+1:n]))/L[k,k]
    return b


In [116]:
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]], np.float32)
display(A)

b = np.array([-3,-1,4])
display(b)

L = choleski(A)
display(L)

x = choleskiSol(L,b)
display(x)

array([[ 2., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  2.]], dtype=float32)

array([-3, -1,  4])

array([[ 1.4142135 ,  0.        ,  0.        ],
       [-0.70710677,  1.2247449 ,  0.        ],
       [ 0.        , -0.81649655,  1.1547005 ]], dtype=float32)

array([-1,  0,  1])

# tri-diagonal matrices

In [117]:
def LUdecomp3(c,d,e):
    n = len(d)
    for k in range(1,n):
        lam = c[k-1]/d[k-1]
        d[k] = d[k] - lam*e[k-1]
        c[k-1] = lam
    return c,d,e

def LUsolve3(c,d,e,b):
    n = len(d)
    for k in range(1,n):
        b[k] = b[k] - c[k-1]*b[k-1]
    b[n-1] = b[n-1]/d[n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - e[k]*b[k+1])/d[k]
    return b

In [118]:
c = np.array([1, 2, 3, 4], np.float32)
d = np.array([1, 2, 3, 4, 5], np.float32)
e = np.array([1, 2, 3, 4], np.float32)
display("c", c)
display("d", d)
display("e", e)

from scipy.sparse import diags
A = diags([c,d,e], [-1, 0, 1]).toarray().copy()
display("A", A)

b = np.array([1,2,3,4,5], np.float32)
display("b", b)

'c'

array([1., 2., 3., 4.], dtype=float32)

'd'

array([1., 2., 3., 4., 5.], dtype=float32)

'e'

array([1., 2., 3., 4.], dtype=float32)

'A'

array([[1., 1., 0., 0., 0.],
       [1., 2., 2., 0., 0.],
       [0., 2., 3., 3., 0.],
       [0., 0., 3., 4., 4.],
       [0., 0., 0., 4., 5.]], dtype=float32)

'b'

array([1., 2., 3., 4., 5.], dtype=float32)

In [119]:
LUc,LUd,LUe = LUdecomp3(c,d,e)
x3 = LUsolve3(LUc,LUd,LUe,b.copy())
x3

array([-0.16326511,  1.1632651 , -0.08163255,  0.30612248,  0.755102  ],
      dtype=float32)

#### verifying solution

In [120]:
np.matmul(A,x3)

array([1., 2., 3., 4., 5.], dtype=float32)

### solving with standard LU

In [121]:
LU=LUdecomp(A.copy())
x = LUsolve(LU,b.copy())

#### verifying solution

In [122]:
display("LU", LU)
display("x", x)
np.matmul(A,x)

'LU'

array([[ 1.        ,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  2.        ,  0.        ,  0.        ],
       [ 0.        ,  2.        , -1.        ,  3.        ,  0.        ],
       [ 0.        ,  0.        , -3.        , 13.        ,  4.        ],
       [ 0.        ,  0.        ,  0.        ,  0.30769232,  3.7692308 ]],
      dtype=float32)

'x'

array([-0.16326511,  1.1632651 , -0.08163255,  0.30612248,  0.755102  ],
      dtype=float32)

array([1., 2., 3., 4., 5.], dtype=float32)

## Gauss-Seidel

In [123]:
def gaussSeidel(iterEqs,x,tol = 1.0e-9):
    omega = 1.0
    k = 10
    p = 1
    for i in range(1,501):
        xOld = x.copy()
        x = iterEqs(x,omega)
        dx = np.sqrt(np.dot(x-xOld,x-xOld))
        print("running iteration %3d  dx=%6.2e" % (i,dx) )
        if dx < tol: return x,i,omega
      # Compute relaxation factor after k+p iterations
        if i == k: dx1 = dx
        if i == k + p:
            dx2 = dx
            omega = 2.0/(1.0 + math.sqrt(1.0 - (dx2/dx1)**(1.0/p)))
    print('Gauss-Seidel failed to converge')
    


In [124]:
A = np.array([[5,1,-2],[0,5,-1],[3,-1,5]], dtype=np.float64)
display(A)

b = np.array([-3,-1,4], dtype=np.float64)
display(b)

def iterEqs(x,omega):
    n = len(x)
    for i in range(n):        
        new  = b[i]
        for j in range(n):
            if(i==j):continue
            new -= A[i,j]*x[j]
        x[i] = ((1-omega)*x[i]) + ((omega/A[i,i]) * new)        
    return x
    
x0 = np.array([0,0,0], np.float32)
x,i,omega = gaussSeidel(iterEqs,x0)
print("x",x)
print("i",i)
print("omega",omega)

array([[ 5.,  1., -2.],
       [ 0.,  5., -1.],
       [ 3., -1.,  5.]])

array([-3., -1.,  4.])

running iteration   1  dx=1.29e+00
running iteration   2  dx=5.91e-01
running iteration   3  dx=1.70e-01
running iteration   4  dx=4.82e-02
running iteration   5  dx=1.37e-02
running iteration   6  dx=3.90e-03
running iteration   7  dx=1.11e-03
running iteration   8  dx=3.16e-04
running iteration   9  dx=8.98e-05
running iteration  10  dx=2.55e-05
running iteration  11  dx=7.25e-06
running iteration  12  dx=2.28e-06
running iteration  13  dx=9.86e-07
running iteration  14  dx=4.86e-07
running iteration  15  dx=2.74e-07
running iteration  16  dx=1.74e-07
running iteration  17  dx=1.00e-07
running iteration  18  dx=4.74e-08
running iteration  19  dx=1.50e-08
running iteration  20  dx=0.00e+00
x [-0.2244898  -0.01360544  0.9319728 ]
i 20
omega 1.0834399612526664


### compare with GausseElimination

In [125]:
gaussElimin(A,b)

array([-0.2244898 , -0.01360544,  0.93197279])